export const sources = [
 {id:'orion',type:'PROTOTYPE',date:'September 25, 2024 · updated September 12, 2025',title:'Meta · Introducing Orion',url:'https://about.fb.com/news/2024/09/introducing-orion-our-first-true-augmented-reality-glasses/',fact:'Transparent-lens AR prototype supporting spatial content and multitasking. Meta identifies size, display quality, and affordability as remaining priorities.',limit:'Orion itself is not a consumer release. The announcement is not proof of all-day battery or an affordable mass-market product.'},
 {id:'hardware',type:'PROTOTYPE ARCHITECTURE',date:'Undated · accessed September 12, 2026',title:'Meta · Orion hardware overview',url:'https://www.meta.com/emerging-tech/orion/',fact:'Describes microLED projectors, silicon-carbide optics, miniaturized sensors, and a wireless pocket compute puck.',limit:'A plausible architecture, not evidence that ordinary-frame size, low cost, and all-day power have been solved simultaneously.'},
 {id:'qualcomm',type:'PLATFORM ARCHITECTURE',date:'November 16, 2022',title:'Qualcomm · Snapdragon AR2',url:'https://www.qualcomm.com/news/releases/2022/11/qualcomm-launches-snapdragon-ar2-designed-to-revolutionize-ar-gl',fact:'Distributed processing keeps latency-sensitive perception on glasses and can offload complex computation to a compatible smartphone, PC, or host. Eye tracking can support foveated rendering.',limit:'A chip-platform announcement, not whole-device battery performance. Our paired-compute recommendation is an engineering proposal.'},
 {id:'emg',type:'PEER-REVIEWED RESEARCH',date:'July 23, 2025',title:'Nature · A generic non-invasive neuromotor interface',url:'https://www.nature.com/articles/s41586-025-09255-w',fact:'Wrist surface electromyography supports continuous control, gestures, and handwriting through models designed to generalize across users.',limit:'Muscle activity, not thought reading. Does not prove facial control or reliability across full delivery shifts.'},
 {id:'display',type:'COMMERCIAL PRODUCT',date:'September 17, 2025',title:'Meta · Ray-Ban Display and Neural Band',url:'https://about.fb.com/news/2025/09/meta-ray-ban-display-ai-glasses-emg-wristband/',fact:'Announced from $799 including the wrist-based Neural Band; US retail availability September 30, 2025. Includes an off-center in-lens display.',limit:'Launch price, not a current prescription package quote. A small display is not equivalent to full spatial AR.'},
 {id:'temple',type:'EXPERIMENTAL SENSING',date:'Online April 27, 2017 · January 2018 issue',title:'Zhang & Amft · Smart-eyeglass chewing detection',url:'https://pubmed.ncbi.nlm.nih.gov/28463209/',fact:'Personally fitted glasses measured temporalis-muscle EMG for chewing detection with ten participants in lab and free-living conditions.',limit:'It studied chewing, not reliable intentional app commands. Facial/temple-muscle input is a proposed research option, not a launch feature.'},
 {id:'instacart',type:'PLATFORM DOCUMENTATION',date:'Updated August 11, 2026',title:'Instacart · In-store product locations',url:'https://docs.instacart.com/catalog/catalog_inventory_file/specifications/in-store-locations',fact:'Retailers can provide aisle, shelf, department, and picking-order information for display in the Shopper app.',limit:'Fields are optional. AR guidance would require platform agreement, sufficient location data, and an appropriate glasses interface.'},
 {id:'amazon',type:'ENTERPRISE DEVELOPMENT',date:'October 22, 2025',title:'Amazon · Smart glasses for delivery associates',url:'https://www.aboutamazon.com/news/transportation/smart-glasses-amazon-delivery-drivers',fact:'Describes package scanning, walking guidance, and delivery-photo workflows. Glasses activate after parking and use a controller with a swappable battery.',limit:'No quantified productivity result reported here. Enterprise development does not establish consumer demand or independent-shopper economics.'},
 {id:'dhl',type:'ENTERPRISE PRECEDENT',date:'May 21, 2019',title:'DHL · Smart-glasses deployment',url:'https://group.dhl.com/en/media-relations/press-releases/2019/dhl-supply-chain-deploys-latest-version-of-smart-glasses-worldwide.html',fact:'Reports commercial use of vision picking across most geographic regions and smart-glasses deployment at freight hubs.',limit:'Structured warehouses differ from public grocery stores. Do not transfer historical pilot efficiency claims to consumer AR.'},
 {id:'aura',type:'COMPETITOR DEMONSTRATION',date:'May 19, 2026',title:'XREAL · Project Aura at Google I/O',url:'https://www.xreal.com/uk/blog/project-aura-google-io-2026',fact:'Demonstrated wired Android XR glasses, spatial content, and DisplayPort-in laptop connectivity, with global launch announced for 2026.',limit:'Demonstration and announced availability are not independent evidence of adoption or professional productivity.'},
 {id:'google',type:'COMPETITOR ANNOUNCEMENT',date:'May 19, 2026',title:'Google · Intelligent eyewear',url:'https://blog.google/products-and-platforms/platforms/android/android-xr-io-2026/',fact:'Describes audio and display glasses, phone pairing, Gemini assistance, and app actions. Audio glasses were announced to launch first in fall 2026.',limit:'No display-glasses release date in this announcement. Google also markets presence and hands-free use; simplicity alone is not a unique Meta claim.'},
 {id:'apple',type:'INTERACTION PRECEDENT',date:'June 5, 2023',title:'Apple · Introducing Vision Pro',url:'https://www.apple.com/newsroom/2023/06/introducing-apple-vision-pro/',fact:'Introduced spatial interaction using eyes, hands, and voice. Looking targets an interface; a deliberate finger gesture selects.',limit:'Headset-scale implementation. Does not demonstrate that the same complete system fits ordinary lightweight glasses.'},
 {id:'visioncouncil',type:'CONSUMER RESEARCH',date:'September 12, 2025',title:'The Vision Council · Smart-eyewear awareness',url:'https://thevisioncouncil.org/blog/latest-report-vision-council-shows-rising-awareness-smart-eyewear-recent-years',fact:'Public release identifies unclear need/purpose and cost as leading reported purchase deterrents.',limit:'The release does not specify the precise denominator for those questions. We do not treat it as a survey of Meta nonbuyers or proof of demand for this proposal.'}
];
