// Source facts describe existing products or published evidence. They do not
// verify the proposed partnerships, fictional order, or untested outcomes below.
export const workSources = [
  {
    id: 'vision-council',
    title: 'The Vision Council · Smart eyewear adoption',
    date: 'September 12, 2025',
    url: 'https://thevisioncouncil.org/blog/latest-report-vision-council-shows-rising-awareness-smart-eyewear-recent-years',
    fact: 'The report identifies unclear purpose and cost as barriers to buying smart eyewear.',
    limit: 'General consumer research, not evidence that delivery workers will buy glasses or that early adopters are exhausted.',
  },
  {
    id: 'instacart',
    title: 'Instacart · 2025 annual report',
    date: 'February 26, 2026',
    url: 'https://www.sec.gov/Archives/edgar/data/1579091/000157909126000018/cart-20251231.htm',
    fact: 'Instacart reported approximately 600,000 monthly active shoppers in December 2025.',
    limit: 'Platform reach, not glasses demand. Frequent workers are a subset; no Meta integration is established by this filing.',
  },
  {
    id: 'meta-sdk',
    title: 'Meta · Build for display glasses',
    date: 'May 14, 2026',
    url: 'https://developers.meta.com/blog/build-for-display-glasses/',
    fact: 'Meta began rolling out developer-preview display access for iOS and Android app extensions and standalone Web Apps.',
    limit: 'Developer-preview capability, not universal phone mirroring, worker-account access, unrestricted distribution or full spatial AR.',
  },
  {
    id: 'spark',
    title: 'Spark Driver · Shopping & Delivery Overview',
    date: 'Accessed September 12, 2026',
    url: 'https://sparkdriverapp-walmart.helpdocs.io/l/en/article/el2mg4pv0m-shopping-delivery-overview',
    fact: 'The phone app documents suggested shopping paths, aisle and section locations, item images, barcode confirmation and substitution decisions.',
    limit: 'Existing Spark phone-app functions. A glasses partnership is proposed, and complete or current store-location coverage is not guaranteed.',
  },
  {
    id: 'meta-display',
    title: 'Meta · Ray-Ban Display launch',
    date: 'September 17, 2025',
    url: 'https://about.fb.com/news/2025/09/meta-ray-ban-display-ai-glasses-emg-wristband/',
    fact: 'Meta Ray-Ban Display launched from $799 including Meta Neural Band, with an in-lens display for short interactions.',
    limit: 'A historical launch price and existing display product, not a price forecast or proof of shelf-anchored AR and ring support.',
  },
  {
    id: 'amazon',
    title: 'Amazon · Delivery-glasses development',
    date: 'October 22, 2025',
    url: 'https://www.aboutamazon.com/news/transportation/smart-glasses-amazon-delivery-drivers',
    fact: 'Amazon described developing glasses for delivery associates, including package identification and walking guidance after parking.',
    limit: 'An industry example, not a Meta partnership, measured savings in this demo, proof of consumer demand or evidence about electricians.',
  },
  {
    id: 'tracking',
    title: 'Google ARCore · Fundamental concepts',
    date: 'Updated October 31, 2024 · accessed September 12, 2026',
    url: 'https://developers.google.com/ar/develop/fundamentals',
    fact: 'ARCore combines visual feature tracking and inertial measurements to estimate device pose; anchors help maintain virtual objects relative to the environment.',
    limit: 'General AR principles on supported devices, not proof of Meta hardware support or shelf-scale accuracy.',
  },
];

// One fictional order, shown as a design walkthrough—not a live integration,
// job offer, camera result, customer conversation, or measured productivity test.
export const walkthroughSteps = [
  {
    id: 'offer',
    kicker: '01 · Simulated offer',
    title: 'Choose the order',
    detail: 'An example partner task lists oat milk and apples. The worker reviews it and chooses whether to accept. This is not a live paid offer.',
    progress: 0,
    task: 'Review before accepting',
    item: 'Oat milk · apples',
    location: 'Example grocery store',
  },
  {
    id: 'find',
    kicker: '02 · Simulated store guidance',
    title: 'Find the aisle',
    detail: 'The first card directs the worker to dairy, aisle 03, for oat milk. This example guidance is a card to read, not a claim of shelf-accurate tracking on today’s glasses.',
    progress: 0.18,
    task: 'Find the first item',
    item: 'Oat milk · 1 carton',
    location: 'Dairy · aisle 03 · example data',
  },
  {
    id: 'verify',
    kicker: '03 · Simulated item check',
    title: 'Check, then confirm',
    detail: 'The worker checks the oat milk and quantity before confirming. If the example barcode result is uncertain, the phone provides manual review. No camera is running in this walkthrough.',
    progress: 0.42,
    task: 'Check and confirm oat milk',
    item: 'Oat milk · 1 carton',
    location: 'Dairy · aisle 03 · phone fallback',
  },
  {
    id: 'produce',
    kicker: '04 · Simulated produce stop',
    title: 'Pick up the apples',
    detail: 'The worker collects apples in produce. This route assumes both requested items are found; the separate product demo illustrates optional substitution and approval. No customer is contacted.',
    progress: 0.62,
    task: 'Collect and confirm apples',
    item: 'Apples · second item',
    location: 'Produce · example data',
  },
  {
    id: 'checkout',
    kicker: '05 · Simulated checkout',
    title: 'Keep checkout familiar',
    detail: 'The worker reviews oat milk and apples on the phone. The original app keeps its checkout and verification steps. This two-item example does not place or pay for an order.',
    progress: 0.83,
    task: 'Review before checkout',
    item: 'Oat milk · apples · two items',
    location: 'Checkout · original app',
  },
  {
    id: 'deliver',
    kicker: '06 · Simulated walking handoff',
    title: 'Hands on the bags',
    detail: 'After parking, the example card switches to walking and drop-off details. Interactive cards stay off while driving. The worker confirms the handoff; no real delivery is recorded.',
    progress: 1,
    task: 'Review the drop-off instructions',
    item: 'Two-item order · ready to hand over',
    location: 'Example address · after parking',
  },
];

export const navigationLayers = [
  {
    id: 'partner-data',
    title: 'Start with permission',
    short: 'Approved partner task data',
    detail: 'A proposed phone-connected companion receives order items, task status and permitted actions through an authorized partner integration. The worker chooses whether to accept available tasks.',
    limit: 'A Meta display SDK does not grant access to another company’s worker accounts. No Instacart or Spark glasses agreement is claimed here.',
  },
  {
    id: 'store-location',
    title: 'Know the store',
    short: 'Store map and indoor location',
    detail: 'Product-location data can identify an aisle or section. Ordinary GPS does not reliably locate the correct shelf; spatial shelf guidance would need a reliable indoor map and localization.',
    limit: 'Store data can be missing or stale. An uncertain location returns the worker to the phone, item list or manual search—not a confidently placed marker.',
  },
  {
    id: 'display-and-tracking',
    title: 'A card first. AR later.',
    short: 'Display cards now; anchored AR as a future prototype',
    detail: 'Near-term cards describe the next task. A future spatial prototype would additionally track the glasses relative to the store and anchor cues to that environment, with accuracy tested in real aisles.',
    limit: 'General visual and inertial tracking principles do not establish that current Meta glasses support dependable shelf-anchored guidance. The spatial view is a concept, not a hardware demonstration.',
  },
  {
    id: 'confirmation',
    title: 'The worker decides',
    short: 'Deliberate confirmation and fallback',
    detail: 'The worker confirms items, substitutions and messages. Uncertain barcode or location results return to manual review; partner rules and customer decisions govern what is permitted.',
    limit: 'The walkthrough uses scripted examples. It does not scan products, contact customers, accept jobs, change orders or demonstrate measured time savings.',
  },
];
